services:

  redis:
    image: redis:7.4
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    restart: always
    build:
      context: ./codegrade_backend
    depends_on:
      redis:
        condition: service_healthy
      prestart:
        condition: service_completed_successfully
    ports:
      - "8050:8000"
    volumes: &common_volume
      - ./codegrade_backend/src:/codegrade_backend/src
      - ./codegrade_backend/database:/codegrade_backend/database
      - ./codegrade_backend/logs:/codegrade_backend/logs
    env_file:
      - .env
    environment: &common_env
      - SQLITE_DATABASE_PATH=${SQLITE_DATABASE_PATH}
      - DOMAIN=${DOMAIN}
      - FRONTEND_HOST=${FRONTEND_HOST?Variable not set}
      - ENVIRONMENT=${ENVIRONMENT}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - SECRET_KEY=${SECRET_KEY?Variable not set}
      - FIRST_SUPERUSER=${FIRST_SUPERUSER?Variable not set}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD?Variable not set}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
      - SENTRY_DSN=${SENTRY_DSN}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_GRADING_QUEUE=${CELERY_GRADING_QUEUE?Variable not set}
      - CELERY_DEFAULT_QUEUE=${CELERY_DEFAULT_QUEUE?Variable not set}
      - EXTERNAL_API_KEY=${EXTERNAL_API_KEY}
    healthcheck:
      test: "curl -s -f http://localhost:8000/api/v1/health-check/ | get -n 1 | grep 200"
      interval: 30s
      timeout: 5s
      retries: 5

  prestart:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    build:
      context: ./codegrade_backend
    command: bash ./scripts/prestart.sh
    depends_on:
      redis:
        condition: service_healthy
    volumes: *common_volume
    environment: *common_env
    env_file:
      - .env

  codegrade-worker:
    entrypoint: ["/bin/bash", "-c", "./celery_entry_point.sh"]
    build:
      context: ./codegrade_backend
    depends_on:
      redis:
        condition: service_healthy
      server:
        condition: service_started
    volumes: *common_volume
    environment: *common_env
    env_file:
      - .env
